# Generated by Django 3.1.6 on 2021-02-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0002_whitelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('url', models.TextField(default='')),
                ('ip', models.TextField(default='')),
            ],
        ),
    ]
